In [1]:
import os
import json
import pandas as pd
from datetime import datetime
from dotenv import load_dotenv

from options import OptionSurface, Deribit, OKX, Bybit
from portfolio_management import Portfolio
from api_client import TradingDeskAPI
from scanner import MarketScanner

In [ ]:
# Initialize all classes and parameters

load_dotenv(r"D:/OneDrive/Trading/Prediction Markets/Moreton Capital/.env")
BASE_URL = os.getenv("BASE_URL")
USER_EMAIL = os.getenv("USER_EMAIL")
USER_PASSWORD = os.getenv("USER_PASSWORD")
JWT_TOKEN = os.getenv("JWT")
DATA_DIR = os.getenv("DATA_DIR")
FRACTION = os.getenv("FRACTION")
MAX_POSITION = os.getenv("MAX_POSITION")
ENTRY_EV_THRESHOLD = os.getenv("ENTRY_EV_THRESHOLD") # require 1% edge, default = 0
EXIT_EV_THRESHOLD = os.getenv("EXIT_EV_THRESHOLD")
print(BASE_URL)

with open(f"{DATA_DIR}/crypto_tag_ids.json", "r") as f:
    crypto_tag_ids = set(json.load(f))

s = OptionSurface()
portfolio = Portfolio()
api = TradingDeskAPI(base_url=BASE_URL, email=USER_EMAIL, password=USER_PASSWORD, token=JWT_TOKEN)
scanner = MarketScanner(api=api)

target_expiry_str = "25DEC26"
target_expiry = datetime.strptime(target_expiry_str, "%d%b%y").strftime("%Y%m%d")

currencies = ["BTC", "ETH"]
# currencies = ["BTC", "ETH", "HYPE", "SOL", "ZEC"]

https://alphasignal-dev.moretoncp.com

In [ ]:
# 1. Get all dfs
orders_df = pd.read_parquet(f"{DATA_DIR}/orders.parquet")
fills_df = pd.read_parquet(f"{DATA_DIR}/fills.parquet")
positions_df = pd.read_parquet(f"{DATA_DIR}/positions.parquet")
realized_pnl_df = pd.read_parquet(f"{DATA_DIR}/realized_pnl.parquet")
equity_df = pd.read_parquet(f"{DATA_DIR}/equity.parquet")

# fills_df = fills_df.iloc[0:0]

In [24]:
# 2. Get newly executed trades
fills_df = portfolio.sync_fills(api=api, fills_df=fills_df)
fills_df

,order_id,condition_id,token_id,outcome,side,price,shares,fee_rate_bps,timestamp,fill_id
0,0x8039083a81a0749075a21658567ad6e0e449ea2ac99e...,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,No,BUY,0.981,4.87,0.0,2026-08-14 08:25:11+00:00,4c3c68e2-7b89-463c-ae03-48b92808eeef

In [10]:
# 3. Reconstruct portfolio
# 4. Calculate realized P&L
positions_df, realized_df = portfolio.reconstruct_positions_fifo(fills_df=fills_df) # new realized_df to overwrite old
realized_df

,condition_id,token_id,outcome,realized_shares,realized_pnl,realized_fees
0,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,No,0.0,0.0,0.0

In [11]:
# 5. Sync positions with api
portfolio.reconcile_positions(api=api, positions_df=positions_df)

POSITIONS SYNCED

In [12]:
# 6. Get latest order state
orders_df = portfolio.sync_orders(api=api, orders_df=orders_df)
orders_df

,order_id,condition_id,token_id,outcome,side,price,requested_size,order_type,status,created_at,cancelled_at
0,0x8039083a81a0749075a21658567ad6e0e449ea2ac99e...,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,NO,buy,0.981,4.877934,GTC,OPEN,2026-08-14 09:28:01.978131+00:00,NaT

In [13]:
# 7. Mark positions to market
positions_df = portfolio.mark_positions_to_market(api=api, positions_df=positions_df)
positions_df

,condition_id,token_id,outcome,shares,cost_basis,avg_entry_price,realized_pnl,realized_shares,realized_fees,current_price,market_value,unrealized_pnl,unrealized_return
0,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,No,4.87,4.77747,0.981,0.0,0.0,0.0,0.985,4.79695,0.01948,0.004077

In [14]:
# 8. Calculate equity
equity_df = portfolio.calculate_equity(api=api, positions_df=positions_df, 
                                realized_df=realized_df, equity_df=equity_df)
equity_df

Equity:  100.01
Return:  0.0131%
Sharpe: N/A
Sortino: N/A

,timestamp,cash,market_value,equity,realized_pnl,unrealized_pnl,daily_return,period_return,sharpe,sortino
0,2026-08-14 07:47:24.047885+00:00,100.00000,0.00000,100.00000,0.0,0.00000,NaN,None,NaN,NaN
1,2026-08-15 14:14:05.272655+00:00,95.21618,4.79695,100.01313,0.0,0.01948,NaN,0.000131,NaN,NaN

In [15]:
# 9. Initialize variance surface
deribit = Deribit(currencies=currencies, target_expiry=target_expiry)
okx = OKX(currencies=currencies, target_expiry=target_expiry)
bybit = Bybit(currencies=currencies, target_expiry=target_expiry)

s.initialize(currencies=currencies, exchanges=[deribit, okx, bybit])

spot: 63048.0 volume24h: 1.9996
spot: 1882.7 volume24h: 13.8911
spot: 63040.9 volume24h: 1937.72974071
spot: 1883.12 volume24h: 29829.973884
spot: 63035.9 volume24h: 3971.899523
spot: 1883.12 volume24h: 27701.52774

In [16]:
# 10. Get current markets
# markets = api.get_markets(limit=10000, liquidity_num_min=10000, volume_num_min=5000) # old api
# all_markets_df = pd.DataFrame(markets)

all_markets_df = api.get_all_markets(DATA_DIR=DATA_DIR, count_limit=10, liquidity_num_min=10000, volume_num_min=5000)
all_markets_df.head()

Fetched 100 markets | Total: 100
Fetched 100 markets | Total: 200
Fetched 100 markets | Total: 300
Fetched 100 markets | Total: 400
Fetched 100 markets | Total: 500
Fetched 100 markets | Total: 600
Fetched 100 markets | Total: 700
Fetched 100 markets | Total: 800
Fetched 100 markets | Total: 900
Fetched 100 markets | Total: 1,000

,id,question,conditionId,slug,resolutionSource,endDate,liquidity,startDate,image,icon,...,negRiskMarketID,oneDayPriceChange,seriesColor,showGmpSeries,showGmpOutcome,umaResolutionStatus,oneHourPriceChange,eventStartTime,gameStartTime,groupItemRange
0,559651,Xi Jinping out before 2027?,0xa467b14d51f01b957109d9cbb1d6c124fab2a089d52e...,xi-jinping-out-before-2027,,2026-12-31T00:00:00Z,255668.90297,2025-07-03T20:37:00.228Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,NaN,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN
1,559652,Will Gavin Newsom win the 2028 Democratic pres...,0x0f49db97f71c68b1e42a6d16e3de93d85dbf7d4148e3...,will-gavin-newsom-win-the-2028-democratic-pres...,,2028-11-07T00:00:00Z,371457.03958,2025-07-11T18:35:56.805Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,0x2c3d7e0eee6f058be3006baabf0d54a07da254ba47fe...,-0.008,,False,False,NaN,NaN,NaN,NaN,NaN
2,559653,Will Alexandria Ocasio-Cortez win the 2028 Dem...,0xe6bcc2f1dd025ce5e1833190f7c60a71171c94f805df...,will-alexandria-ocasio-cortez-win-the-2028-dem...,,2028-11-07T00:00:00Z,437459.92072,2025-07-11T18:35:59.075Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,0x2c3d7e0eee6f058be3006baabf0d54a07da254ba47fe...,-0.024,,False,False,NaN,NaN,NaN,NaN,NaN
3,559654,Will Pete Buttigieg win the 2028 Democratic pr...,0x4c325469d9b516ef4e6b8f73a81a12607dec075e3c2f...,will-pete-buttigieg-win-the-2028-democratic-pr...,,2028-11-07T00:00:00Z,454592.31471,2025-07-11T18:35:58.818Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,0x2c3d7e0eee6f058be3006baabf0d54a07da254ba47fe...,NaN,,False,False,NaN,NaN,NaN,NaN,NaN
4,559655,Will Josh Shapiro win the 2028 Democratic pres...,0xd65891729ce093cc12236856837eba1a0872fc7998fd...,will-josh-shapiro-win-the-2028-democratic-pres...,,2028-11-07T00:00:00Z,430084.17586,2025-07-11T18:36:01.098Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,0x2c3d7e0eee6f058be3006baabf0d54a07da254ba47fe...,NaN,,False,False,NaN,NaN,NaN,NaN,NaN

In [17]:
# 11. Scan markets
markets_df, opportunities_df = scanner.scan_market(markets_df=all_markets_df, s=s, crypto_tag_ids=crypto_tag_ids)
opportunities_df.head()

iv 0.07330828953123085
p_touch_above: 1.0 p_touch_below: 0.0

BTC
buy_yes_ev: 0.96689727
sell_yes_ev: -0.97297113
buy_no_ev: -0.97297113
sell_no_ev: 0.9668972699999999
buy_yes_kelly: 0.5
sell_yes_kelly: -17.998738571016844
buy_no_kelly: -17.998738571016855
sell_no_kelly: 0.5
iv 0.5843791417764115
p_touch_above: 0.0006 p_touch_below: 1.0

BTC
buy_yes_ev: -0.015434249999999998
sell_yes_ev: 0.012433719999999999
buy_no_ev: 0.012433720000000025
sell_no_ev: -0.015434250000000026
buy_yes_kelly: -0.007842879693729177
sell_yes_kelly: 0.4769827800505151
buy_no_kelly: 0.4769827800505151
sell_no_kelly: -0.007842879693729191
iv 0.5780910872579328
p_touch_above: 0.00095 p_touch_below: 1.0

BTC
buy_yes_ev: -0.023622969999999997
sell_yes_ev: 0.019543879999999996
buy_no_ev: 0.01954387999999996
sell_no_ev: -0.023622970000000024
buy_yes_kelly: -0.012109040078579736
sell_yes_kelly: 0.4768223489158714
buy_no_kelly: 0.4768223489158714
sell_no_kelly: -0.01210904007857975
iv 0.5743358365182031
p_touch_above: 0.00139 p_touch_below: 1.0

BTC
buy_yes_ev: -0.022116119999999996
sell_yes_ev: 0.018170870000000002
buy_no_ev: 0.018170870000000065
sell_no_ev: -0.022116120000000072
buy_yes_kelly: -0.01132424915965679
sell_yes_kelly: 0.46446988298577724
buy_no_kelly: 0.46446988298577735
sell_no_kelly: -0.01132424915965683
iv 0.5564865387885678
p_touch_above: 0.00213 p_touch_below: 1.0

BTC
buy_yes_ev: -0.02457625
sell_yes_ev: 0.02023032
buy_no_ev: 0.020230319999999993
sell_no_ev: -0.024576250000000043
buy_yes_kelly: -0.012625299402158908
sell_yes_kelly: 0.45237098574617896
buy_no_kelly: 0.452370985746179
sell_no_kelly: -0.012625299402158929
iv 0.523932995512402
p_touch_above: 0.00207 p_touch_below: 1.0

BTC
buy_yes_ev: -0.028901130000000004
sell_yes_ev: 0.02309103
buy_no_ev: 0.023091030000000026
sell_no_ev: -0.02890113000000007
buy_yes_kelly: -0.014912419482404071
sell_yes_kelly: 0.45886495902592217
buy_no_kelly: 0.4588649590259222
sell_no_kelly: -0.014912419482404106
iv 0.5149508608767062
p_touch_above: 0.00378 p_touch_below: 1.0

BTC
buy_yes_ev: -0.030388320000000003
sell_yes_ev: 0.025117269999999997
buy_no_ev: 0.025117269999999973
sell_no_ev: -0.03038832000000003
buy_yes_kelly: -0.0157316852559651
sell_yes_kelly: 0.4345958978131844
buy_no_kelly: 0.43459589781318436
sell_no_kelly: -0.015731685255965112
iv 0.48570045084358404
p_touch_above: 0.00456 p_touch_below: 1.0

BTC
buy_yes_ev: -0.03280425
sell_yes_ev: 0.027140920000000002
buy_no_ev: 0.027140920000000023
sell_no_ev: -0.032804249999999986
buy_yes_kelly: -0.017038765701356925
sell_yes_kelly: 0.42807779711125105
buy_no_kelly: 0.4280777971112511
sell_no_kelly: -0.017038765701356918
iv 0.4699794566306301
p_touch_above: 0.00795 p_touch_below: 1.0

BTC
buy_yes_ev: -0.03580233
sell_yes_ev: 0.029362
buy_no_ev: 0.029362000000000013
sell_no_ev: -0.03580233000000001
buy_yes_kelly: -0.018720218162727655
sell_yes_kelly: 0.3934659090909091
buy_no_kelly: 0.3934659090909091
sell_no_kelly: -0.018720218162727658
iv 0.44464874772867774
p_touch_above: 0.01271 p_touch_below: 1.0

BTC
buy_yes_ev: -0.040615000000000005
sell_yes_ev: 0.024602
buy_no_ev: 0.024602000000000013
sell_no_ev: -0.04061500000000007
buy_yes_kelly: -0.021451395674333854
sell_yes_kelly: 0.3296794596912522
buy_no_kelly: 0.32967945969125223
sell_no_kelly: -0.02145139567433389
iv 0.42603035457401045
p_touch_above: 0.02333 p_touch_below: 1.0

BTC
buy_yes_ev: -0.040618000000000015
sell_yes_ev: 0.023345000000000005
buy_no_ev: 0.023345000000000025
sell_no_ev: -0.040618000000000015
buy_yes_kelly: -0.021696444214637657
sell_yes_kelly: 0.25008034279592933
buy_no_kelly: 0.25008034279592944
sell_no_kelly: -0.021696444214637657
iv 0.40892837963950807
p_touch_above: 0.04739 p_touch_below: 1.0

BTC
buy_yes_ev: -0.04834299999999999
sell_yes_ev: 0.027457999999999996
buy_no_ev: 0.027457999999999906
sell_no_ev: -0.04834299999999995
buy_yes_kelly: -0.026730489999082122
sell_yes_kelly: 0.1834250748182984
buy_no_kelly: 0.183425074818298
sell_no_kelly: -0.0267304899990821
iv 0.4268901424425773
p_touch_above: 1.0 p_touch_below: 0.62279

BTC
buy_yes_ev: 0.02573800000000004
sell_yes_ev: -0.06994699999999995
buy_no_ev: -0.06994699999999995
sell_no_ev: 0.025737999999999955
buy_yes_kelly: 0.03193712340053807
sell_yes_kelly: -0.06326117903274524
buy_no_kelly: -0.06326117903274524
sell_no_kelly: 0.03193712340053798
iv 0.4922483639581899
p_touch_above: 1.0 p_touch_below: 0.29992

BTC
buy_yes_ev: 0.026451999999999976
sell_yes_ev: -0.06304500000000002
buy_no_ev: -0.06304500000000007
sell_no_ev: 0.026451999999999948
buy_yes_kelly: 0.018204291070455243
sell_yes_kelly: -0.1330765171503958
buy_no_kelly: -0.13307651715039595
sell_no_kelly: 0.018204291070455222
iv 0.6037892589988177
p_touch_above: 1.0 p_touch_below: 0.14026

BTC
buy_yes_ev: 0.03395999999999999
sell_yes_ev: -0.055993000000000015
buy_no_ev: -0.05599300000000003
sell_no_ev: 0.033960000000000046
buy_yes_kelly: 0.018999664316884858
sell_yes_kelly: -0.332235631979304
buy_no_kelly: -0.3322356319793041
sell_no_kelly: 0.018999664316884886
iv 0.7562558077815354
p_touch_above: 1.0 p_touch_below: 0.06768

BTC
buy_yes_ev: 0.03244622999999999
sell_yes_ev: -0.03784831999999999
buy_no_ev: -0.03784831999999997
sell_no_ev: 0.03244622999999995
buy_yes_kelly: 0.016815591690020077
sell_yes_kelly: -0.6343645413198317
buy_no_kelly: -0.6343645413198308
sell_no_kelly: 0.016815591690020053
iv 0.7808358791077656
p_touch_above: 0.00021 p_touch_below: 1.0

ETH
buy_yes_ev: -0.01368817
sell_yes_ev: 0.01002847
buy_no_ev: 0.01002847
sell_no_ev: -0.013688170000000043
buy_yes_kelly: -0.006940545886625116
sell_yes_kelly: 0.4897445614432625
buy_no_kelly: 0.4897445614432625
sell_no_kelly: -0.006940545886625139
iv 0.7521935652096582
p_touch_above: 0.00083 p_touch_below: 1.0

ETH
buy_yes_ev: -0.021609130000000004
sell_yes_ev: 0.017797999999999998
buy_no_ev: 0.017797999999999977
sell_no_ev: -0.021609129999999976
buy_yes_kelly: -0.011052575171099066
sell_yes_kelly: 0.4777217092548851
buy_no_kelly: 0.47772170925488505
sell_no_kelly: -0.011052575171099052
iv 0.7434446440869281
p_touch_above: 0.00108 p_touch_below: 1.0

ETH
buy_yes_ev: -0.024559680000000004
sell_yes_ev: 0.02034703
buy_no_ev: 0.020347030000000012
sell_no_ev: -0.024559680000000056
buy_yes_kelly: -0.012602976278836973
sell_yes_kelly: 0.4747981871495956
buy_no_kelly: 0.4747981871495956
sell_no_kelly: -0.012602976278837
iv 0.7012478610247267
p_touch_above: 0.00109 p_touch_below: 1.0

ETH
buy_yes_ev: -0.02561625
sell_yes_ev: 0.02127032
buy_no_ev: 0.02127031999999999
sell_no_ev: -0.025616250000000042
buy_yes_kelly: -0.013159567705022251
sell_yes_kelly: 0.47562646688419485
buy_no_kelly: 0.47562646688419485
sell_no_kelly: -0.013159567705022272
iv 0.7082334314184691
p_touch_above: 0.00211 p_touch_below: 1.0

ETH
buy_yes_ev: -0.02672897
sell_yes_ev: 0.02211732
buy_no_ev: 0.02211732000000005
sell_no_ev: -0.026728970000000022
buy_yes_kelly: -0.013761348105164394
sell_yes_kelly: 0.45645411873868014
buy_no_kelly: 0.4564541187386802
sell_no_kelly: -0.013761348105164405
iv 0.680464447875424
p_touch_above: 0.00255 p_touch_below: 1.0

ETH
buy_yes_ev: -0.017754729999999996
sell_yes_ev: 0.011415749999999999
buy_no_ev: 0.011415749999999999
sell_no_ev: -0.01775472999999999
buy_yes_kelly: -0.009061353332858285
sell_yes_kelly: 0.4087052252832823
buy_no_kelly: 0.4087052252832823
sell_no_kelly: -0.009061353332858282
iv 0.6529979925663237
p_touch_above: 0.00402 p_touch_below: 1.0

ETH
buy_yes_ev: -0.03014832
sell_yes_ev: 0.024877269999999996
buy_no_ev: 0.024877269999999972
sell_no_ev: -0.030148320000000027
buy_yes_kelly: -0.01560744000445295
sell_yes_kelly: 0.43044325640449765
buy_no_kelly: 0.4304432564044976
sell_no_kelly: -0.015607440004452964
iv 0.6364581333621158
p_touch_above: 0.00654 p_touch_below: 1.0

ETH
buy_yes_ev: -0.03508353
sell_yes_ev: 0.02516092
buy_no_ev: 0.02516092000000002
sell_no_ev: -0.03508353000000008
buy_yes_kelly: -0.018303626548761158
sell_yes_kelly: 0.3968484195411363
buy_no_kelly: 0.3968484195411364
sell_no_kelly: -0.0183036265487612
iv 0.6051543656051506
p_touch_above: 0.01122 p_touch_below: 1.0

ETH
buy_yes_ev: -0.042105000000000004
sell_yes_ev: 0.026091999999999997
buy_no_ev: 0.02609200000000001
sell_no_ev: -0.042105000000000066
buy_yes_kelly: -0.022238360577811814
sell_yes_kelly: 0.3496462264150943
buy_no_kelly: 0.34964622641509435
sell_no_kelly: -0.022238360577811853
iv 0.5799080779029363
p_touch_above: 0.02225 p_touch_below: 1.0

ETH
buy_yes_ev: -0.04169800000000001
sell_yes_ev: 0.024425000000000002
buy_no_ev: 0.024425000000000023
sell_no_ev: -0.04169800000000001
buy_yes_kelly: -0.022273335242059208
sell_yes_kelly: 0.2616497054097483
buy_no_kelly: 0.26164970540974836
sell_no_kelly: -0.022273335242059208
iv 0.556637249227632
p_touch_above: 0.04652 p_touch_below: 1.0

ETH
buy_yes_ev: -0.05978
sell_yes_ev: 0.037746999999999996
buy_no_ev: 0.03774699999999998
sell_no_ev: -0.05977999999999996
buy_yes_kelly: -0.03344522770504644
sell_yes_kelly: 0.22397261086783674
buy_no_kelly: 0.2239726108678367
sell_no_kelly: -0.03344522770504641
iv 0.561241413102564
p_touch_above: 1.0 p_touch_below: 0.54704

ETH
buy_yes_ev: 0.11201068000000003
sell_yes_ev: -0.14705776999999998
buy_no_ev: -0.14705776999999998
sell_no_ev: 0.11201067999999989
buy_yes_kelly: 0.09912963978944891
sell_yes_kelly: -0.18383037916459435
buy_no_kelly: -0.18383037916459435
sell_no_kelly: 0.0991296397894488
iv 0.6789349425451119
p_touch_above: 1.0 p_touch_below: 0.16419

ETH
buy_yes_ev: 0.04733700000000002
sell_yes_ev: -0.07049000000000001
buy_no_ev: -0.07049000000000001
sell_no_ev: 0.04733700000000003
buy_yes_kelly: 0.02680018162321789
sell_yes_kelly: -0.3761472785485593
buy_no_kelly: -0.3761472785485593
sell_no_kelly: 0.026800181623217897
iv 0.7574784311534087
p_touch_above: 1.0 p_touch_below: 0.09355

ETH
buy_yes_ev: 0.008397999999999989
sell_yes_ev: -0.028107
buy_no_ev: -0.028107000000000076
sell_no_ev: 0.008397999999999989
buy_yes_kelly: 0.00458983350239602
sell_yes_kelly: -0.2147441284782177
buy_no_kelly: -0.21474412847821853
sell_no_kelly: 0.00458983350239602

,id,question,conditionId,slug,resolutionSource,endDate,liquidity,startDate,image,icon,...,buy_yes_ev,sell_yes_ev,buy_no_ev,sell_no_ev,buy_yes_kelly,sell_yes_kelly,buy_no_kelly,sell_no_kelly,best_ev,best_action
166,573656,"Will Bitcoin hit $150k by December 31, 2026?",0x02deb9538f5c123373adaa4ee6217b01745f1662bc90...,will-bitcoin-hit-150k-by-december-31-2026,,2027-01-01T05:00:00Z,188955.98603,2025-08-07T16:29:32.879Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,0.966897,-0.972971,-0.972971,0.966897,0.500000,-17.998739,-17.998739,0.500000,0.966897,buy_yes_ev
761,701552,"Will Ethereum dip to $1,500 by December 31, 2026?",0xcf25ccc8360f3952139fb5e3f14cb9bb0636cb53d0e3...,will-ethereum-dip-to-1500-by-december-31-2026-...,,2027-01-01T05:00:00Z,105649.65637,2025-11-24T19:27:14.681Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,0.112011,-0.147058,-0.147058,0.112011,0.099130,-0.183830,-0.183830,0.099130,0.112011,buy_yes_ev
762,701553,"Will Ethereum dip to $1,000 by December 31, 2026?",0xacb33346b59a2a3770e2391b7d1b0e77d8dcdcf840a6...,will-ethereum-dip-to-1000-by-december-31-2026-...,,2027-01-01T05:00:00Z,107228.5736,2025-11-24T19:27:19.011Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,0.047337,-0.070490,-0.070490,0.047337,0.026800,-0.376147,-0.376147,0.026800,0.047337,sell_no_ev
760,701549,"Will Ethereum reach $3,500 by December 31, 2026?",0x42945ea5657d6f6e77969a06661b29d6f6295083d1ef...,will-ethereum-reach-3500-by-december-31-2026,,2027-01-01T05:00:00Z,54550.872,2025-11-24T19:27:16.702Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,-0.059780,0.037747,0.037747,-0.059780,-0.033445,0.223973,0.223973,-0.033445,0.037747,sell_yes_ev
748,701503,"Will Bitcoin dip to $35,000 by December 31, 2026?",0x2745c38ff0617cb345c1d2df19b4f74ea777508e0741...,will-bitcoin-dip-to-35000-by-december-31-2026-...,,2027-01-01T05:00:00Z,130875.7839,2025-11-24T19:07:19.763Z,https://polymarket-upload.s3.us-east-2.amazona...,https://polymarket-upload.s3.us-east-2.amazona...,...,0.033960,-0.055993,-0.055993,0.033960,0.019000,-0.332236,-0.332236,0.019000,0.033960,sell_no_ev

In [18]:
# 12. manage cancel orders
orders_df = portfolio.manage_open_orders(api=api, orders_df=orders_df, markets_df=markets_df, 
                ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)
orders_df

,order_id,condition_id,token_id,outcome,side,price,requested_size,order_type,status,created_at,cancelled_at
0,0x8039083a81a0749075a21658567ad6e0e449ea2ac99e...,0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...,9699347185440015640867052761315094444335927219...,NO,buy,0.981,4.877934,GTC,OPEN,2026-08-14 09:28:01.978131+00:00,NaT

In [19]:
# 13. Risk management
orders_df = portfolio.run_risk_management(api=api, positions_df=positions_df, 
            markets_df=markets_df, orders_df=orders_df, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)

pos: condition_id         0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...
token_id             9699347185440015640867052761315094444335927219...
outcome                                                             No
shares                                                            4.87
cost_basis                                                     4.77747
avg_entry_price                                                  0.981
realized_pnl                                                       0.0
realized_shares                                                    0.0
realized_fees                                                      0.0
current_price                                                    0.985
market_value                                                   4.79695
unrealized_pnl                                                 0.01948
unrealized_return                                             0.004077
Name: 0, dtype: object
market: id                                                             701486
question            Will Bitcoin reach $200,000 by December 31, 2026?
conditionId         0xac32e73aa9e0dae801d88d4f81efd2ef3fa0f04b815f...
slug                will-bitcoin-reach-200000-by-december-31-2026-...
resolutionSource
                                          ...
sell_yes_kelly                                               0.476983
buy_no_kelly                                                 0.476983
sell_no_kelly                                               -0.007843
best_ev                                                      0.012434
best_action                                                 buy_no_ev
Name: 735, Length: 133, dtype: object

KeyError: 'question'

In [ ]:
# 14. New opportunities
orders_df = portfolio.run_new_opportunities(api=api, opportunities_df=opportunities_df, orders_df=orders_df, 
            ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, MAX_POSITION=MAX_POSITION, FRACTION=FRACTION)

In [ ]:
# 15. Safe dfs
portfolio.save_snapshots(DATA_DIR, markets_df, "markets")
portfolio.save_snapshots(DATA_DIR, opportunities_df, "opportunities")
portfolio.save(DATA_DIR, orders_df, "orders")
portfolio.save(DATA_DIR, fills_df, "fills")
portfolio.save(DATA_DIR, positions_df, "positions")
portfolio.save(DATA_DIR, realized_df, "realized_pnl")
portfolio.save(DATA_DIR, equity_df, "equity")

In [23]:
portfolio.save_snapshots(DATA_DIR, markets_df, "markets")
portfolio.save_snapshots(DATA_DIR, opportunities_df, "opportunities")

ValueError: Can't infer object conversion type: 166    [{'id': '36173', 'ticker': 'when-will-bitcoin-...
735    [{'id': '89502', 'ticker': 'what-price-will-bi...
736    [{'id': '89502', 'ticker': 'what-price-will-bi...
737    [{'id': '89502', 'ticker': 'what-price-will-bi...
738    [{'id': '89502', 'ticker': 'what-price-will-bi...
739    [{'id': '89502', 'ticker': 'what-price-will-bi...
740    [{'id': '89502', 'ticker': 'what-price-will-bi...
741    [{'id': '89502', 'ticker': 'what-price-will-bi...
742    [{'id': '89502', 'ticker': 'what-price-will-bi...
743    [{'id': '89502', 'ticker': 'what-price-will-bi...
744    [{'id': '89502', 'ticker': 'what-price-will-bi...
745    [{'id': '89502', 'ticker': 'what-price-will-bi...
746    [{'id': '89502', 'ticker': 'what-price-will-bi...
747    [{'id': '89502', 'ticker': 'what-price-will-bi...
748    [{'id': '89502', 'ticker': 'what-price-will-bi...
749    [{'id': '89502', 'ticker': 'what-price-will-bi...
750    [{'id': '89519', 'ticker': 'what-price-will-et...
751    [{'id': '89519', 'ticker': 'what-price-will-et...
752    [{'id': '89519', 'ticker': 'what-price-will-et...
753    [{'id': '89519', 'ticker': 'what-price-will-et...
754    [{'id': '89519', 'ticker': 'what-price-will-et...
755    [{'id': '89519', 'ticker': 'what-price-will-et...
756    [{'id': '89519', 'ticker': 'what-price-will-et...
757    [{'id': '89519', 'ticker': 'what-price-will-et...
758    [{'id': '89519', 'ticker': 'what-price-will-et...
759    [{'id': '89519', 'ticker': 'what-price-will-et...
760    [{'id': '89519', 'ticker': 'what-price-will-et...
761    [{'id': '89519', 'ticker': 'what-price-will-et...
762    [{'id': '89519', 'ticker': 'what-price-will-et...
763    [{'id': '89519', 'ticker': 'what-price-will-et...
Name: events, dtype: object

In [ ]:
ENTRY_EV_THRESHOLD = 0.01   # require 1% edge, default = 0
EXIT_EV_THRESHOLD = 0.02
FRACTION = 0.25
MAX_POSITION = 0.05

load_dotenv(r"D:/OneDrive/Trading/Prediction Markets/Moreton Capital/.env")
BASE_URL = os.getenv("BASE_URL")
USER_EMAIL = os.getenv("USER_EMAIL")
USER_PASSWORD = os.getenv("USER_PASSWORD")
JWT_TOKEN = os.getenv("JWT")
DATA_DIR = os.getenv("DATA_DIR")
print(BASE_URL)

with open(f"{DATA_DIR}/crypto_tag_ids.json", "r") as f:
    crypto_tag_ids = set(json.load(f))

s = OptionSurface()
portfolio = Portfolio()
api = TradingDeskAPI(base_url=BASE_URL, email=USER_EMAIL, password=USER_PASSWORD, token=JWT_TOKEN)
scanner = MarketScanner(api=api)

target_expiry_str = "25DEC26"
target_expiry = datetime.strptime(target_expiry_str, "%d%b%y").strftime("%Y%m%d")

currencies = ["BTC", "ETH"]

for i in range(1):
    # 1. Get all dfs
    orders_df = pd.read_parquet(f"{DATA_DIR}/orders.parquet")
    fills_df = pd.read_parquet(f"{DATA_DIR}/fills.parquet")
    positions_df = pd.read_parquet(f"{DATA_DIR}/positions.parquet")
    realized_pnl_df = pd.read_parquet(f"{DATA_DIR}/realized_pnl.parquet") # old pnl df
    equity_df = pd.read_parquet(f"{DATA_DIR}/equity.parquet")

    # 2. Get newly executed trades
    fills_df = portfolio.sync_fills(api=api, fills_df=fills_df)

    # 3. Reconstruct portfolio
    # 4. Calculate realized P&L
    positions_df, realized_df = portfolio.reconstruct_positions_fifo(fills_df=fills_df) # new realized_df to overwrite old

    # 5. Sync positions with api
    portfolio.reconcile_positions(api=api, positions_df=positions_df)

    # 6. Get latest order state
    orders_df = portfolio.sync_orders(api=api, orders_df=orders_df)

    # 7. Mark positions to market
    positions_df = portfolio.mark_positions_to_market(api=api, positions_df=positions_df)

    # 8. Calculate equity
    equity_df = portfolio.calculate_equity(api=api, positions_df=positions_df, 
                                    realized_df=realized_df, equity_df=equity_df)

    # 9. Initialize variance surface
    deribit = Deribit(currencies=currencies, target_expiry=target_expiry)
    okx = OKX(currencies=currencies, target_expiry=target_expiry)
    bybit = Bybit(currencies=currencies, target_expiry=target_expiry)

    s.initialize(currencies=currencies, exchanges=[deribit, okx, bybit])

    # 10. Get current markets
    all_markets_df = api.get_all_markets(DATA_DIR=DATA_DIR, count_limit=10, liquidity_num_min=10000, volume_num_min=5000)

    # 11. Scan markets
    markets_df, opportunities_df = scanner.scan_market(markets_df=all_markets_df, s=s, crypto_tag_ids=crypto_tag_ids)

    # 12. manage cancel orders
    orders_df = portfolio.manage_open_orders(api=api, orders_df=orders_df, markets_df=markets_df, 
                ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)

    # 13. Risk management
    orders_df = portfolio.run_risk_management(api=api, positions_df=positions_df, 
            markets_df=markets_df, orders_df=orders_df, EXIT_EV_THRESHOLD=EXIT_EV_THRESHOLD)

    # 14. New opportunities
    orders_df = portfolio.run_new_opportunities(api=api, opportunities_df=opportunities_df, orders_df=orders_df, 
            ENTRY_EV_THRESHOLD=ENTRY_EV_THRESHOLD, MAX_POSITION=MAX_POSITION, FRACTION=FRACTION)

    # 15. Safe dfs
    portfolio.save_snapshots(DATA_DIR, markets_df, "markets")
    portfolio.save_snapshots(DATA_DIR, opportunities_df, "opportunities")
    portfolio.save(DATA_DIR, orders_df, "orders")
    portfolio.save(DATA_DIR, fills_df, "fills")
    portfolio.save(DATA_DIR, positions_df, "positions")
    portfolio.save(DATA_DIR, realized_df, "realized_pnl")
    portfolio.save(DATA_DIR, equity_df, "equity")

    # time.sleep(300)

In [ ]:
# Polymarket    Model (exchanges: deribit, bybit, okx)    Edge

# 80k Dec-26        22%          20%       +2%
# 90k Dec-26        14%          12%       +2%
# 100k Dec-26        9.5%         5.9%     +3.6%
# 110k Dec-26        7%           4%       +3%
# 120k Dec-26        5%           2%       +3%

In [ ]:
# Keep trading journal

# Your thesis.
# Why you think the market is mispriced.
# Position size.
# Exit criteria.
# What actually happened.

In [ ]:
# Stage 2 — Semi-automated execution

# The bot does:

# find opportunities
# calculate size
# prepare orders

# You approve:

# BUY YES
# Market: BTC above $150k
# Price: 0.43
# Size: $500
# Expected edge: +8%

# Click "confirm".

# This is useful because prediction markets can have:

# ambiguous wording
# resolution risks
# sudden news events

In [ ]:
# Day 1 — API connection + market ingestion

# Goal:

# Can I pull markets automatically?

# Build:

# get_markets()

# Output:

# {
#  "condition_id": "...",
#  "question": "Will X happen?",
#  "tokens": [
#     {
#       "token_id": "YES",
#       "price": 0.42
#     },
#     {
#       "token_id": "NO",
#       "price": 0.58
#     }
#  ]
# }

# Store:

# markets

# condition_id
# question
# yes_token
# no_token
# created_time
# Day 2 — Historical snapshots

# Goal:

# Can I reconstruct what the market looked like yesterday?

# Every 5 minutes:

# while True:

#     markets = api.get_markets()

#     for m in markets:
#         database.save_snapshot(m)

#     sleep(300)

# Database:

# market_snapshots

# timestamp
# condition_id
# yes_price
# no_price
# volume
# Day 3 — Order book collection

# Now collect microstructure data.

# For selected markets:

# get_orderbook(token_id)

# Store:

# orderbook_snapshots

# timestamp

# token_id

# best_bid
# best_ask

# bid_depth
# ask_depth

# Calculate:

# Spread
# spread=ask−bid

# Example:

# Bid:
# 0.42

# Ask:
# 0.46

# Spread:
# 4 cents
# Day 4 — Build your scanner

# Your first scanner should be dumb but useful.

# Signal 1: Large moves
# if abs(price_change_24h) > 0.10:
#     flag()

# Example:

# AI model release

# Yesterday:
# 35%

# Today:
# 52%

# Move:
# +17%
# Signal 2: Liquidity opportunities
# if spread > 0.08:
#     flag()
# Signal 3: Volume spikes
# if volume_today > 5 * average_volume:
#     flag()

# Your output:

# TOP MARKETS TO REVIEW

# 1.
# Question:
# Will Fed cut rates?

# Price:
# 42%

# 24h move:
# +12%

# Reason:
# Large movement


# 2.
# Question:
# Will Company X acquire Y?

# Price:
# 33%

# Spread:
# 11 cents

# Reason:
# Wide market
# Day 5 — Add your probability workflow

# Do NOT automate this yet.

# Create a manual table:

# trade_journal.csv

# market,current_price,my_probability,edge,reason
# Fed cut,0.42,0.55,0.13,"Inflation falling"
# AI launch,0.35,0.45,0.10,"Company comments"

# The key question:

# Market probability:
# 42%

# My probability:
# 55%

# Difference:
# +13%
# Day 6 — Paper trading

# Before your C++ engine touches anything:

# Create:

# paper_buy(
#     market,
#     price,
#     size
# )

# Track:

# Position:
# YES Fed cut

# Entry:
# 42c

# Size:
# $100

# Current:
# 48c

# P&L:
# +$14
# Day 7 — Analytics

# Calculate:

# Return
# profit / capital
# Drawdown

# Largest loss from peak.

# Sortino

# Track:

# returns
# negative returns only

# Your output:

# Paper Portfolio

# Trades:
# 18

# Win rate:
# 61%

# Return:
# +8.4%

# Max drawdown:
# -2.1%

# Sortino:
# 2.4